site_name: PYRA Token / Exchange

theme:
  name: 'material'
 
nav:
    - Get started:
      - Introduction: index.md
      - Why invest?: get-started/invest.md
      - Buy/Sell: get-started/buy.md
      - Dividends: get-started/divs.md
      
    - Masternode/Affiliate:
      - Guide: masternode/guide.md
      
    - Wallets:
        - Metamask (best): wallets/metamask.md
        - Trust Wallet Mobile: wallets/trust.md
        - Bianance Smart Chain Wallet: wallets/bnb.md
        
    - dApp Ecosystem:
        - Dice: dapp-ecosystem/comingsoon.md
   
markdown_extensions:
    - attr_list: